project_id = "jgybqgblhlmnbstlpape"

[functions.validate-coupon]
verify_jwt = false

[functions.track-order]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = false
